name: Setup PlatformIO

inputs:
  python-version:
    description: 'Installs PlatformIO and necessary dependencies.'
    required: false
    default: '3.9'

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # TODO: set via input?
        submodules: 'recursive'

    - name: Cache pip
      id: cache-pip
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          ~/.platformio/.cache
        key: ${{ runner.os }}-${{ inputs.python-version }}-pio }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install PlatformIO Core
      run: pip install --upgrade platformio

    - name: Install intelhex
      run: pip install --upgrade intelhex

