name: FW Build / Test (Conditional Job PoC)

on: [push,pull_request]

jobs:
  determine-builds:
    name: Evaluate Required Builds
    runs-on: ubuntu-20.04
    timeout-minutes: 1
    # Map a step output to a job output
    outputs:
      arm-tag_newton-m3-nrf52811: ${{steps.filter.outputs.arm-tag_newton-m3-nrf52811 }}
      arm-tag_nrf52811-pio-ap: ${{steps.filter.outputs.arm-tag_nrf52811-pio-ap }}
      arm-tag_88MZ100: ${{steps.filter.outputs.arm-tag_88MZ100 }}
      esp32-ap: ${{steps.filter.outputs.esp32-ap }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          token: ${{ github.token }}
          filters: .github/path-filters.yml

  tag-build:
    name: Build Tag FWs
    needs: [determine-builds]
    runs-on: ubuntu-22.04
    steps:
      - uses: ./.github/actions/setup-pio
      - name: ARM_Tag_FW/Newton_M3_nRF52811
        if: ${{ needs.determine-builds.outputs.arm-tag_newton-m3-nrf52811 == 'true' }}
        run: |
          pio --version
          cd ARM_Tag_FW/Newton_M3_nRF52811
          pio run --environment Newton_M3_Universal

      - name: ARM_Tag_FW/nrf52811_Platformio_AP
        if: ${{ needs.determine-builds.outputs.arm-tag_nrf52811-pio-ap == 'true' }}
        run: |
          cd ARM_Tag_FW/nrf52811_Platformio_AP
          pio run --environment nrf52811_OEPL_AP

      - name: ARM_Tag_FW/88MZ100_OpenEpaperLink_7.4
        if: ${{ needs.determine-builds.outputs.arm-tag_88MZ100 == 'true' }}
        run: |
          echo "POC: this shouldn't run"
          exit 1

  ap-build:
    name: Build AP FWs
    needs: [determine-builds]
    if: ${{ needs.determine-builds.outputs.esp32-ap == 'true' }}
    runs-on: ubuntu-22.04
    steps:
      - uses: ./.github/actions/setup-pio
      - name: Build OpenEPaperLink_Mini_AP
        run: |
          cd ESP32_AP-Flasher
          pio run --environment OpenEPaperLink_Mini_AP
          pio run --target buildfs --environment OpenEPaperLink_Mini_AP

      - name: Build OpenEPaperLink_AP_and_Flasher
        run: |
          cd ESP32_AP-Flasher
          pio run --environment OpenEPaperLink_AP_and_Flasher
          pio run --target buildfs --environment OpenEPaperLink_AP_and_Flasher

      - name: Build ESP32_S3_16_8_YELLOW_AP
        run: |
          cd ESP32_AP-Flasher
          pio run --environment ESP32_S3_16_8_YELLOW_AP
          pio run --target buildfs --environment ESP32_S3_16_8_YELLOW_AP

      - name: OpenEPaperLink_Mini_AP_v4
        run: |
          cd ESP32_AP-Flasher
          pio run --environment OpenEPaperLink_Mini_AP_v4
          pio run --target buildfs --environment OpenEPaperLink_Mini_AP_v4


