name: Setup PlatformIO Environment

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
        default: '3.9'

jobs:
  setup:
    runs-on: ubuntu-22.04
    outputs:
      cache-key: ${{ steps.cache-pip.outputs.cache-key }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Cache pip
        id: cache-pip
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-${{ inputs.python-version }}-pio }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Install intelhex
        run: pip install --upgrade intelhex
